// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jczawpxfipfceactrwry.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjemF3cHhmaXBmY2VhY3Ryd3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjI3NzMsImV4cCI6MjA2NTI5ODc3M30.qfGvXNCiJzi4eMQkNzwXUdVTqyzak9hpTpl-3VgEx_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);